//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLifter.BusinessLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLifter.BusinessLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio disabled.
        /// </summary>
        internal static string AUDIOPLAYER_CRASHED_CAPTION {
            get {
                return ResourceManager.GetString("AUDIOPLAYER_CRASHED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to an error with the audio player, sound has been disabled. Restart MemoryLifter to enable sound..
        /// </summary>
        internal static string AUDIOPLAYER_CRASHED_TEXT {
            get {
                return ResourceManager.GetString("AUDIOPLAYER_CRASHED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryLifter USB-Stick on {0}.
        /// </summary>
        internal static string CSH_CONNECTION_NAME {
            get {
                return ResourceManager.GetString("CSH_CONNECTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;{0}&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        {1}
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ERROR_PAGE {
            get {
                return ResourceManager.GetString("ERROR_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pool is empty!.
        /// </summary>
        internal static string EXCEPTION_POOL_EMPTY {
            get {
                return ResourceManager.GetString("EXCEPTION_POOL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?guid={0}.
        /// </summary>
        internal static string ExtensionURI_Suffix {
            get {
                return ResourceManager.GetString("ExtensionURI_Suffix", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty module!.
        /// </summary>
        internal static string LEARNING_MODULES_PAGE_EMPTY_LM {
            get {
                return ResourceManager.GetString("LEARNING_MODULES_PAGE_EMPTY_LM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Images!.
        /// </summary>
        internal static string LEARNING_MODULES_PAGE_NO_IMAGES {
            get {
                return ResourceManager.GetString("LEARNING_MODULES_PAGE_NO_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string LOCAL_MODULE {
            get {
                return ResourceManager.GetString("LOCAL_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?id={0}.
        /// </summary>
        internal static string MediaURI_Suffix {
            get {
                return ResourceManager.GetString("MediaURI_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .key.
        /// </summary>
        internal static string STICK_KEY_EXTENSION {
            get {
                return ResourceManager.GetString("STICK_KEY_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMKeys.
        /// </summary>
        internal static string STICK_KEY_FOLDER {
            get {
                return ResourceManager.GetString("STICK_KEY_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string TEACHER_DEFAULT {
            get {
                return ResourceManager.GetString("TEACHER_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Nice Guy.
        /// </summary>
        internal static string TEACHER_NICEGUY {
            get {
                return ResourceManager.GetString("TEACHER_NICEGUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasional Learner.
        /// </summary>
        internal static string TEACHER_OCCASIONAL {
            get {
                return ResourceManager.GetString("TEACHER_OCCASIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict.
        /// </summary>
        internal static string TEACHER_STRICT {
            get {
                return ResourceManager.GetString("TEACHER_STRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click button for example:.
        /// </summary>
        internal static string XSL_CLICKFORE {
            get {
                return ResourceManager.GetString("XSL_CLICKFORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click button for question:.
        /// </summary>
        internal static string XSL_CLICKFORQ {
            get {
                return ResourceManager.GetString("XSL_CLICKFORQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correct answer is:.
        /// </summary>
        internal static string XSL_CORRECT {
            get {
                return ResourceManager.GetString("XSL_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card has been demoted to Box 1!.
        /// </summary>
        internal static string XSL_DEMOTE_MESSAGE {
            get {
                return ResourceManager.GetString("XSL_DEMOTE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylesheet Error.
        /// </summary>
        internal static string XSL_ERROR_CAPTION {
            get {
                return ResourceManager.GetString("XSL_ERROR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when compiling {0}.&lt;br /&gt;
        ///Your stylesheet or linked parts may contain errors.&lt;br /&gt;
        ///If you are unsure what to do, restore the original file in &quot;Tools - Style Editor&quot;..
        /// </summary>
        internal static string XSL_ERROR_TEXT {
            get {
                return ResourceManager.GetString("XSL_ERROR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer was correct!.
        /// </summary>
        internal static string XSL_FEEDBACK_CORRECT {
            get {
                return ResourceManager.GetString("XSL_FEEDBACK_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer was wrong!.
        /// </summary>
        internal static string XSL_FEEDBACK_WRONG {
            get {
                return ResourceManager.GetString("XSL_FEEDBACK_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to show the image..
        /// </summary>
        internal static string XSL_LISTENING_MODE_IMAGE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("XSL_LISTENING_MODE_IMAGE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This card has reached the highest box..
        /// </summary>
        internal static string XSL_PROMOTE_HIGHEST_MESSAGE {
            get {
                return ResourceManager.GetString("XSL_PROMOTE_HIGHEST_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card has been promoted to Box {box_number}!.
        /// </summary>
        internal static string XSL_PROMOTE_MESSAGE {
            get {
                return ResourceManager.GetString("XSL_PROMOTE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click image to show original size..
        /// </summary>
        internal static string XSL_RESIZE_PICTURE {
            get {
                return ResourceManager.GetString("XSL_RESIZE_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click image to show smaller size..
        /// </summary>
        internal static string XSL_RESTORE_PICTURE {
            get {
                return ResourceManager.GetString("XSL_RESTORE_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to demote the card?.
        /// </summary>
        internal static string XSL_SELFASSESMENT_DEMOTE_MESSAGE {
            get {
                return ResourceManager.GetString("XSL_SELFASSESMENT_DEMOTE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to promote the card?.
        /// </summary>
        internal static string XSL_SELFASSESMENT_PROMOTE_MESSAGE {
            get {
                return ResourceManager.GetString("XSL_SELFASSESMENT_PROMOTE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered:.
        /// </summary>
        internal static string XSL_YOUENTERED {
            get {
                return ResourceManager.GetString("XSL_YOUENTERED", resourceCulture);
            }
        }
    }
}
