//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLifter.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLifter.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap button_close {
            get {
                object obj = ResourceManager.GetObject("button_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckButtonCross3 {
            get {
                object obj = ResourceManager.GetObject("CheckButtonCross3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Launch External Application.
        /// </summary>
        internal static string ERROR_LAUNCH_EXTERNAL_APPLICATION_CAPTION {
            get {
                return ResourceManager.GetString("ERROR_LAUNCH_EXTERNAL_APPLICATION_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryLifter failed to launch an external application..
        /// </summary>
        internal static string ERROR_LAUNCH_EXTERNAL_APPLICATION_TEXT {
            get {
                return ResourceManager.GetString("ERROR_LAUNCH_EXTERNAL_APPLICATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Feed.
        /// </summary>
        internal static string FeedTreeNode_Name {
            get {
                return ResourceManager.GetString("FeedTreeNode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFLINE.
        /// </summary>
        internal static string FeedTreeNode_Text_Offline {
            get {
                return ResourceManager.GetString("FeedTreeNode_Text_Offline", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_gif {
            get {
                object obj = ResourceManager.GetObject("folder_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon folder_ico {
            get {
                object obj = ResourceManager.GetObject("folder_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_jpg {
            get {
                object obj = ResourceManager.GetObject("folder_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_saved_search {
            get {
                object obj = ResourceManager.GetObject("folder_saved_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_saved_search_gif {
            get {
                object obj = ResourceManager.GetObject("folder_saved_search_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon folder_saved_search_ico {
            get {
                object obj = ResourceManager.GetObject("folder_saved_search_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_saved_search_jpg {
            get {
                object obj = ResourceManager.GetObject("folder_saved_search_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gadu_blue {
            get {
                object obj = ResourceManager.GetObject("gadu_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gadu_grau {
            get {
                object obj = ResourceManager.GetObject("gadu_grau", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gadu_green {
            get {
                object obj = ResourceManager.GetObject("gadu_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gadu_orange {
            get {
                object obj = ResourceManager.GetObject("gadu_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gadu_pink {
            get {
                object obj = ResourceManager.GetObject("gadu_pink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gadu_red {
            get {
                object obj = ResourceManager.GetObject("gadu_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gadu_yellow {
            get {
                object obj = ResourceManager.GetObject("gadu_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap green_arrow1 {
            get {
                object obj = ResourceManager.GetObject("green_arrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap green_arrow2 {
            get {
                object obj = ResourceManager.GetObject("green_arrow2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap learning_16_gif {
            get {
                object obj = ResourceManager.GetObject("learning_16_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ML {
            get {
                object obj = ResourceManager.GetObject("ML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MLSplashScreen {
            get {
                object obj = ResourceManager.GetObject("MLSplashScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MLSplashScreen_144x33_white {
            get {
                object obj = ResourceManager.GetObject("MLSplashScreen_144x33_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap network {
            get {
                object obj = ResourceManager.GetObject("network", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap network_gif {
            get {
                object obj = ResourceManager.GetObject("network_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon network_ico {
            get {
                object obj = ResourceManager.GetObject("network_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap network_jpg {
            get {
                object obj = ResourceManager.GetObject("network_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap network_offline {
            get {
                object obj = ResourceManager.GetObject("network_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap network_offline_gif {
            get {
                object obj = ResourceManager.GetObject("network_offline_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon network_offline_ico {
            get {
                object obj = ResourceManager.GetObject("network_offline_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap network_offline_jpg {
            get {
                object obj = ResourceManager.GetObject("network_offline_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_search {
            get {
                object obj = ResourceManager.GetObject("system_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_search_gif {
            get {
                object obj = ResourceManager.GetObject("system_search_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap usbDrive {
            get {
                object obj = ResourceManager.GetObject("usbDrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
