//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLifterErrorHandler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLifterErrorHandler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_bw {
            get {
                object obj = ResourceManager.GetObject("arrow_down_bw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_color {
            get {
                object obj = ResourceManager.GetObject("arrow_down_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_color_pressed {
            get {
                object obj = ResourceManager.GetObject("arrow_down_color_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up_bw {
            get {
                object obj = ResourceManager.GetObject("arrow_up_bw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up_color {
            get {
                object obj = ResourceManager.GetObject("arrow_up_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up_color_pressed {
            get {
                object obj = ResourceManager.GetObject("arrow_up_color_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but the main error report cannot be omitted. It must be included..
        /// </summary>
        internal static string ERROR_CANNOT_DISABLE_ERRORREPORT {
            get {
                return ResourceManager.GetString("ERROR_CANNOT_DISABLE_ERRORREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occured within the Error Handler. An error report could not be generated.{0}{1}.
        /// </summary>
        internal static string ERROR_INTERNALERROR {
            get {
                return ResourceManager.GetString("ERROR_INTERNALERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... Sorry for the inconvenience!
        ///MemoryLifter has encountered a problem and needs to close..
        /// </summary>
        internal static string ERROR_OCCURED_INFORMATION_MESSAGE_FATAL {
            get {
                return ResourceManager.GetString("ERROR_OCCURED_INFORMATION_MESSAGE_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... Sorry for the inconvenience!
        ///MemoryLifter has encountered a problem..
        /// </summary>
        internal static string ERROR_OCCURED_INFORMATION_MESSAGE_NOT_FATAL {
            get {
                return ResourceManager.GetString("ERROR_OCCURED_INFORMATION_MESSAGE_NOT_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Error Report Upload.
        /// </summary>
        internal static string ERROR_TRANSMIT_CANCELUPLOAD {
            get {
                return ResourceManager.GetString("ERROR_TRANSMIT_CANCELUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your error report could not be successfully transmitted, another transmission attempt will be made later..
        /// </summary>
        internal static string ERROR_TRANSMIT_ERROR {
            get {
                return ResourceManager.GetString("ERROR_TRANSMIT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending MemoryLifter Error Report....
        /// </summary>
        internal static string ERROR_TRANSMIT_SENDING {
            get {
                return ResourceManager.GetString("ERROR_TRANSMIT_SENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending MemoryLifter Error Report... {0:0%}.
        /// </summary>
        internal static string ERROR_TRANSMIT_SENDSTAT {
            get {
                return ResourceManager.GetString("ERROR_TRANSMIT_SENDSTAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server did not accept the error report..
        /// </summary>
        internal static string ERROR_TRANSMIT_SERVERERROR {
            get {
                return ResourceManager.GetString("ERROR_TRANSMIT_SERVERERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .zip.
        /// </summary>
        internal static string ERRORFILE_EXTENSION {
            get {
                return ResourceManager.GetString("ERRORFILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorReport.xml.
        /// </summary>
        internal static string ERRORFILE_NAME {
            get {
                return ResourceManager.GetString("ERRORFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception/Message.
        /// </summary>
        internal static string ERRORREPORTPATH_MESSAGE {
            get {
                return ResourceManager.GetString("ERRORREPORTPATH_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception/Stacktrace.
        /// </summary>
        internal static string ERRORREPORTPATH_STACKTRACE {
            get {
                return ResourceManager.GetString("ERRORREPORTPATH_STACKTRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Description.
        /// </summary>
        internal static string ERRORREPORTPATH_USERDESCRIPTION {
            get {
                return ResourceManager.GetString("ERRORREPORTPATH_USERDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Email.
        /// </summary>
        internal static string ERRORREPORTPATH_USEREMAIL {
            get {
                return ResourceManager.GetString("ERRORREPORTPATH_USEREMAIL", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap face_blushing {
            get {
                object obj = ResourceManager.GetObject("face_blushing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap face_surprise {
            get {
                object obj = ResourceManager.GetObject("face_surprise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MLIcon48 {
            get {
                object obj = ResourceManager.GetObject("MLIcon48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLifter.exe.
        /// </summary>
        internal static string MLIFTER_MAINPROGRAM {
            get {
                return ResourceManager.GetString("MLIFTER_MAINPROGRAM", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap trayicon_frame {
            get {
                object obj = ResourceManager.GetObject("trayicon_frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trayicon_stop {
            get {
                object obj = ResourceManager.GetObject("trayicon_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
