//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLifterSettingsManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLifterSettingsManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap chapter_16 {
            get {
                object obj = ResourceManager.GetObject("chapter_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] clear_all_user_profiles {
            get {
                object obj = ResourceManager.GetObject("clear_all_user_profiles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customSettings {
            get {
                object obj = ResourceManager.GetObject("customSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Module version not supported!.
        /// </summary>
        internal static string DBVERSION_NOT_SUPPORTED_CAPTION {
            get {
                return ResourceManager.GetString("DBVERSION_NOT_SUPPORTED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryLifter will try to update your Learning Module now..
        /// </summary>
        internal static string DBVERSION_NOT_SUPPORTED_CONTENT {
            get {
                return ResourceManager.GetString("DBVERSION_NOT_SUPPORTED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database version of your Learning Module is not supported..
        /// </summary>
        internal static string DBVERSION_NOT_SUPPORTED_MAIN {
            get {
                return ResourceManager.GetString("DBVERSION_NOT_SUPPORTED_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like to upgrade the Learning Module?.
        /// </summary>
        internal static string DBVERSION_NOT_SUPPORTED_UPGRADE {
            get {
                return ResourceManager.GetString("DBVERSION_NOT_SUPPORTED_UPGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update Learning Module!.
        /// </summary>
        internal static string DBVERSION_NOT_SUPPORTED_UPGRADE_FAILED_CAPTION {
            get {
                return ResourceManager.GetString("DBVERSION_NOT_SUPPORTED_UPGRADE_FAILED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your system administrator or the MemoryLifter support team..
        /// </summary>
        internal static string DBVERSION_NOT_SUPPORTED_UPGRADE_FAILED_CONTENT {
            get {
                return ResourceManager.GetString("DBVERSION_NOT_SUPPORTED_UPGRADE_FAILED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryLifter failed to update your Learning Module..
        /// </summary>
        internal static string DBVERSION_NOT_SUPPORTED_UPGRADE_FAILED_MAIN {
            get {
                return ResourceManager.GetString("DBVERSION_NOT_SUPPORTED_UPGRADE_FAILED_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Learning Module.
        /// </summary>
        internal static string DIC_ERROR_LOADING_CAPTION {
            get {
                return ResourceManager.GetString("DIC_ERROR_LOADING_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading Learning Module {0}..
        /// </summary>
        internal static string DIC_ERROR_LOADING_TEXT {
            get {
                return ResourceManager.GetString("DIC_ERROR_LOADING_TEXT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap empty {
            get {
                object obj = ResourceManager.GetObject("empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Module Extension Data (*.zip)|*.zip.
        /// </summary>
        internal static string EXTENSION_DATAFILEFILTER {
            get {
                return ResourceManager.GetString("EXTENSION_DATAFILEFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Module Extension (*.mlx)|*.mlx.
        /// </summary>
        internal static string EXTENSION_FILEFILTER {
            get {
                return ResourceManager.GetString("EXTENSION_FILEFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Extension.
        /// </summary>
        internal static string EXTENSION_REPLACE_CAPTION {
            get {
                return ResourceManager.GetString("EXTENSION_REPLACE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The learning module already contains the extension &apos;{0}&apos;. Replace?.
        /// </summary>
        internal static string EXTENSION_REPLACE_TEXT {
            get {
                return ResourceManager.GetString("EXTENSION_REPLACE_TEXT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap learning_16 {
            get {
                object obj = ResourceManager.GetObject("learning_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not possible to open Learning Module.
        /// </summary>
        internal static string LM_IS_PROTECTED_CAPTION {
            get {
                return ResourceManager.GetString("LM_IS_PROTECTED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Learning module you try to open is content protected!.
        /// </summary>
        internal static string LM_IS_PROTECTED_CONTENT {
            get {
                return ResourceManager.GetString("LM_IS_PROTECTED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ask your administrator!.
        /// </summary>
        internal static string LM_IS_PROTECTED_TEXT {
            get {
                return ResourceManager.GetString("LM_IS_PROTECTED_TEXT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap noSettings {
            get {
                object obj = ResourceManager.GetObject("noSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryLifter File (*.odx)|*.odx.
        /// </summary>
        internal static string ODX_FILEFILTER {
            get {
                return ResourceManager.GetString("ODX_FILEFILTER", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sort_asc_16 {
            get {
                object obj = ResourceManager.GetObject("sort_asc_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
