//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLifterUpdateHandler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLifterUpdateHandler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find update logic!.
        /// </summary>
        internal static string Exception_CouldNotFindUpdateLogic {
            get {
                return ResourceManager.GetString("Exception_CouldNotFindUpdateLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading update logic!.
        /// </summary>
        internal static string Exception_ErrorLoadingUpdateLogic {
            get {
                return ResourceManager.GetString("Exception_ErrorLoadingUpdateLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates available..
        /// </summary>
        internal static string TASK_DIALOG_NoNewVersionFound_Caption {
            get {
                return ResourceManager.GetString("TASK_DIALOG_NoNewVersionFound_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryLifter will check periodically for updates..
        /// </summary>
        internal static string TASK_DIALOG_NoNewVersionFound_Text {
            get {
                return ResourceManager.GetString("TASK_DIALOG_NoNewVersionFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Updates Found.
        /// </summary>
        internal static string TASK_DIALOG_NoNewVersionFound_Title {
            get {
                return ResourceManager.GetString("TASK_DIALOG_NoNewVersionFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while starting the update!.
        /// </summary>
        internal static string TaskDialog_ErrorStartingUpdate_Content {
            get {
                return ResourceManager.GetString("TaskDialog_ErrorStartingUpdate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Starting Update.
        /// </summary>
        internal static string TaskDialog_ErrorStartingUpdate_Title {
            get {
                return ResourceManager.GetString("TaskDialog_ErrorStartingUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes
        ///        ///Check for newer beta versions.|No
        ///Check only for newer stable releases..
        /// </summary>
        internal static string TaskDialog_UpdateToBeta_Buttons {
            get {
                return ResourceManager.GetString("TaskDialog_UpdateToBeta_Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update to a beta version?.
        /// </summary>
        internal static string TaskDialog_UpdateToBeta_Caption {
            get {
                return ResourceManager.GetString("TaskDialog_UpdateToBeta_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta versions are published more often and you can test new features, but they may be unstable..
        /// </summary>
        internal static string TaskDialog_UpdateToBeta_Text {
            get {
                return ResourceManager.GetString("TaskDialog_UpdateToBeta_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta Update.
        /// </summary>
        internal static string TaskDialog_UpdateToBeta_Title {
            get {
                return ResourceManager.GetString("TaskDialog_UpdateToBeta_Title", resourceCulture);
            }
        }
    }
}
