//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLifter.GenerateTestData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLifter.GenerateTestData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Learning Module....
        /// </summary>
        internal static string COPYTO_STATUS_MESSAGE {
            get {
                return ResourceManager.GetString("COPYTO_STATUS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DIC_ERROR_LOADING_CAPTION {
            get {
                return ResourceManager.GetString("DIC_ERROR_LOADING_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while importing Learning Module.
        /// </summary>
        internal static string DIC_ERROR_LOADING_TEXT {
            get {
                return ResourceManager.GetString("DIC_ERROR_LOADING_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card number.
        /// </summary>
        internal static string ERROR_CARD_NUM_CAPTION {
            get {
                return ResourceManager.GetString("ERROR_CARD_NUM_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of asked cards needs to be between {0} and {1}..
        /// </summary>
        internal static string ERROR_CARD_NUM_TEXT {
            get {
                return ResourceManager.GetString("ERROR_CARD_NUM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR_GENERATE_CAPTION {
            get {
                return ResourceManager.GetString("ERROR_GENERATE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating the test data ({0})..
        /// </summary>
        internal static string ERROR_GENERATE_TEXT {
            get {
                return ResourceManager.GetString("ERROR_GENERATE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Learning Module!.
        /// </summary>
        internal static string ERROR_NO_LM_SELECTED_CAPTION {
            get {
                return ResourceManager.GetString("ERROR_NO_LM_SELECTED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a learning module from the list..
        /// </summary>
        internal static string ERROR_NO_LM_SELECTED_TEXT {
            get {
                return ResourceManager.GetString("ERROR_NO_LM_SELECTED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid session number.
        /// </summary>
        internal static string ERROR_SESSION_NUM_CAPTION {
            get {
                return ResourceManager.GetString("ERROR_SESSION_NUM_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of sessions needs to be between {0} and {1}..
        /// </summary>
        internal static string ERROR_SESSION_NUM_TEXT {
            get {
                return ResourceManager.GetString("ERROR_SESSION_NUM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}/{2})....
        /// </summary>
        internal static string GENERATE_STATUS_MESSAGE {
            get {
                return ResourceManager.GetString("GENERATE_STATUS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating....
        /// </summary>
        internal static string GENERATING {
            get {
                return ResourceManager.GetString("GENERATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        internal static string IMPORTING {
            get {
                return ResourceManager.GetString("IMPORTING", resourceCulture);
            }
        }
    }
}
