//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLifterTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLifterTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] homer_avi {
            get {
                object obj = ResourceManager.GetObject("homer_avi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap homer_jpg {
            get {
                object obj = ResourceManager.GetObject("homer_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream homer_wav {
            get {
                return ResourceManager.GetStream("homer_wav", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap homer2_jpg {
            get {
                object obj = ResourceManager.GetObject("homer2_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\MLifter.DAL\DB\PostgreSQL\MLifterDB.sql.
        /// </summary>
        internal static string MLIFTERDBSQL {
            get {
                return ResourceManager.GetString("MLIFTERDBSQL", resourceCulture);
            }
        }
        
        internal static byte[] StartupFolders {
            get {
                object obj = ResourceManager.GetObject("StartupFolders", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\MLifter.UnitTests\Resources\homer.wav.
        /// </summary>
        internal static string TESTAUDIO {
            get {
                return ResourceManager.GetString("TESTAUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\MLifter.UnitTests\Resources\homer.jpg.
        /// </summary>
        internal static string TESTIMAGE_1 {
            get {
                return ResourceManager.GetString("TESTIMAGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\MLifter.UnitTests\Resources\homer2.jpg.
        /// </summary>
        internal static string TESTIMAGE_2 {
            get {
                return ResourceManager.GetString("TESTIMAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\MLifter.UnitTests\Resources\homer.avi.
        /// </summary>
        internal static string TESTVIDEO {
            get {
                return ResourceManager.GetString("TESTVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniCodeTestData.txt.
        /// </summary>
        internal static string UNICODETSTDATA {
            get {
                return ResourceManager.GetString("UNICODETSTDATA", resourceCulture);
            }
        }
    }
}
