//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityAdminSuite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurityAdminSuite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Error.
        /// </summary>
        internal static string CONNECTION_ERROR_FAILURE_CAPTION {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR_FAILURE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to database!.
        /// </summary>
        internal static string CONNECTION_ERROR_FAILURE_TEXT {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR_FAILURE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Error.
        /// </summary>
        internal static string CONNECTION_ERROR_NO_CONNECTION_AVAILABLE_CAPTION {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR_NO_CONNECTION_AVAILABLE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you are using MemoryLifter 2.4, or that the configuration files are located in &quot;%AppData%\{0}&quot;!.
        /// </summary>
        internal static string CONNECTION_ERROR_NO_CONNECTION_AVAILABLE_DETAILS {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR_NO_CONNECTION_AVAILABLE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database connection found!.
        /// </summary>
        internal static string CONNECTION_ERROR_NO_CONNECTION_AVAILABLE_TEXT {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR_NO_CONNECTION_AVAILABLE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security warning.
        /// </summary>
        internal static string CONNECTION_ERROR_PERMISSION_CAPTION {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR_PERMISSION_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not allowed to edit access permissions..
        /// </summary>
        internal static string CONNECTION_ERROR_PERMISSION_TEXT {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR_PERMISSION_TEXT", resourceCulture);
            }
        }
    }
}
