//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLifter.AudioTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLifter.AudioTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap backward_active_expertmode {
            get {
                object obj = ResourceManager.GetObject("backward_active_expertmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backward_inactive_expertmode {
            get {
                object obj = ResourceManager.GetObject("backward_inactive_expertmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really close?.
        /// </summary>
        internal static string CLOSE_CAPTION {
            get {
                return ResourceManager.GetString("CLOSE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to close?.
        /// </summary>
        internal static string CLOSE_TEXT {
            get {
                return ResourceManager.GetString("CLOSE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This delays are cutted from the end and the beginning of the recording to minimize gaps and remove noise....
        /// </summary>
        internal static string DELAY_DESCRIPTION {
            get {
                return ResourceManager.GetString("DELAY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Learning Module.
        /// </summary>
        internal static string DIC_ERROR_LOADING_CAPTION {
            get {
                return ResourceManager.GetString("DIC_ERROR_LOADING_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Learning Module.
        /// </summary>
        internal static string DIC_ERROR_LOADING_LOCKED_CAPTION {
            get {
                return ResourceManager.GetString("DIC_ERROR_LOADING_LOCKED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading Learning Module {0}.
        ///The file may be in use by another application, e.g. MemoryLifter. Please close it and try again..
        /// </summary>
        internal static string DIC_ERROR_LOADING_LOCKED_TEXT {
            get {
                return ResourceManager.GetString("DIC_ERROR_LOADING_LOCKED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Learning Module.
        /// </summary>
        internal static string DIC_ERROR_LOADING_PROTECTED_CAPTION {
            get {
                return ResourceManager.GetString("DIC_ERROR_LOADING_PROTECTED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Learning Module is content protected..
        /// </summary>
        internal static string DIC_ERROR_LOADING_PROTECTED_TEXT {
            get {
                return ResourceManager.GetString("DIC_ERROR_LOADING_PROTECTED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading Learning Module {0}..
        /// </summary>
        internal static string DIC_ERROR_LOADING_TEXT {
            get {
                return ResourceManager.GetString("DIC_ERROR_LOADING_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|2.
        /// </summary>
        internal static string ENCODING_AVAILABLE_CHANNELS {
            get {
                return ResourceManager.GetString("ENCODING_AVAILABLE_CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22050|44100|48000.
        /// </summary>
        internal static string ENCODING_AVAILABLE_SAMPLING_RATES {
            get {
                return ResourceManager.GetString("ENCODING_AVAILABLE_SAMPLING_RATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ENCODING_NONE {
            get {
                return ResourceManager.GetString("ENCODING_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#0.000} kHz.
        /// </summary>
        internal static string ENCODING_SAMPLINGRATE_TOSTRINGFORMAT {
            get {
                return ResourceManager.GetString("ENCODING_SAMPLINGRATE_TOSTRINGFORMAT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap forward_active_expertmode {
            get {
                object obj = ResourceManager.GetObject("forward_active_expertmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forward_inactive_expertmode {
            get {
                object obj = ResourceManager.GetObject("forward_inactive_expertmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://memorylifter.codeplex.com/wikipage?title=Recorder.
        /// </summary>
        internal static string HOWTO_URL {
            get {
                return ResourceManager.GetString("HOWTO_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Card reached. Jump to the end?.
        /// </summary>
        internal static string JUMP_TO_END_TEXT {
            get {
                return ResourceManager.GetString("JUMP_TO_END_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End reached.
        /// </summary>
        internal static string JUMP_TO_OTHER_END_CAPTION {
            get {
                return ResourceManager.GetString("JUMP_TO_OTHER_END_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Card reached. Jump to the beginning?.
        /// </summary>
        internal static string JUMP_TO_OTHER_END_TEXT {
            get {
                return ResourceManager.GetString("JUMP_TO_OTHER_END_TEXT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap keyboard_layout {
            get {
                object obj = ResourceManager.GetObject("keyboard_layout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer ({0}).
        /// </summary>
        internal static string LISTBOXFIELDS_ANSWER_TEXT {
            get {
                return ResourceManager.GetString("LISTBOXFIELDS_ANSWER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex. Answer ({0}).
        /// </summary>
        internal static string LISTBOXFIELDS_EXANSWER_TEXT {
            get {
                return ResourceManager.GetString("LISTBOXFIELDS_EXANSWER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex. Question ({0}).
        /// </summary>
        internal static string LISTBOXFIELDS_EXQUESTION_TEXT {
            get {
                return ResourceManager.GetString("LISTBOXFIELDS_EXQUESTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question ({0}).
        /// </summary>
        internal static string LISTBOXFIELDS_QUESTION_TEXT {
            get {
                return ResourceManager.GetString("LISTBOXFIELDS_QUESTION_TEXT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap long_green_horizontal {
            get {
                object obj = ResourceManager.GetObject("long_green_horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap long_green_vertical {
            get {
                object obj = ResourceManager.GetObject("long_green_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap long_grey_horizontal {
            get {
                object obj = ResourceManager.GetObject("long_grey_horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap long_grey_vertical {
            get {
                object obj = ResourceManager.GetObject("long_grey_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap long_orange_horizontal {
            get {
                object obj = ResourceManager.GetObject("long_orange_horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap long_orange_vertical {
            get {
                object obj = ResourceManager.GetObject("long_orange_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mp3.
        /// </summary>
        internal static string MP3_EXTENSION {
            get {
                return ResourceManager.GetString("MP3_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple selection detected.
        /// </summary>
        internal static string MULTIPLE_KEY_ASSIGNMENT_ERROR_CAPTION {
            get {
                return ResourceManager.GetString("MULTIPLE_KEY_ASSIGNMENT_ERROR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is selected more than one Time:
        ///.
        /// </summary>
        internal static string MULTIPLE_KEY_ASSIGNMENT_ERROR_TEXT {
            get {
                return ResourceManager.GetString("MULTIPLE_KEY_ASSIGNMENT_ERROR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        internal static string NO_ITEM_TO_RECORD_CAPTION {
            get {
                return ResourceManager.GetString("NO_ITEM_TO_RECORD_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item to record selected!
        ///
        ///Select at least one!.
        /// </summary>
        internal static string NO_ITEM_TO_RECORD_TEXT {
            get {
                return ResourceManager.GetString("NO_ITEM_TO_RECORD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (No Text!).
        /// </summary>
        internal static string NO_TEXT_MESSAGE {
            get {
                return ResourceManager.GetString("NO_TEXT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio device.
        /// </summary>
        internal static string NO_WAVEIN_DEVICE_CAPTION {
            get {
                return ResourceManager.GetString("NO_WAVEIN_DEVICE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recording audio device found! Please verify that the audio equipment is set up properly..
        /// </summary>
        internal static string NO_WAVEIN_DEVICE_TEXT {
            get {
                return ResourceManager.GetString("NO_WAVEIN_DEVICE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio device.
        /// </summary>
        internal static string NO_WAVEOUT_DEVICE_CAPTION {
            get {
                return ResourceManager.GetString("NO_WAVEOUT_DEVICE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playback audio device found! Please verify that the audio equipment is set up properly..
        /// </summary>
        internal static string NO_WAVEOUT_DEVICE_TEXT {
            get {
                return ResourceManager.GetString("NO_WAVEOUT_DEVICE_TEXT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap numpad_layout {
            get {
                object obj = ResourceManager.GetObject("numpad_layout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap play_active_expertmode {
            get {
                object obj = ResourceManager.GetObject("play_active_expertmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap play_inactive_expertmode {
            get {
                object obj = ResourceManager.GetObject("play_inactive_expertmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rec_active_expertmode {
            get {
                object obj = ResourceManager.GetObject("rec_active_expertmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rec_active_simplemode {
            get {
                object obj = ResourceManager.GetObject("rec_active_simplemode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rec_inactive_expertmode {
            get {
                object obj = ResourceManager.GetObject("rec_inactive_expertmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open last Learning Module.
        /// </summary>
        internal static string RELOAD_LAST_DIC_CAPTION {
            get {
                return ResourceManager.GetString("RELOAD_LAST_DIC_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue|Select other Learning Module.
        /// </summary>
        internal static string RELOAD_LAST_DIC_COMMANDS {
            get {
                return ResourceManager.GetString("RELOAD_LAST_DIC_COMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue recording of the last used Learning Module?.
        /// </summary>
        internal static string RELOAD_LAST_DIC_TEXT {
            get {
                return ResourceManager.GetString("RELOAD_LAST_DIC_TEXT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap simplemode {
            get {
                object obj = ResourceManager.GetObject("simplemode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap small_green {
            get {
                object obj = ResourceManager.GetObject("small_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap small_grey {
            get {
                object obj = ResourceManager.GetObject("small_grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap small_orange {
            get {
                object obj = ResourceManager.GetObject("small_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap spacer_green {
            get {
                object obj = ResourceManager.GetObject("spacer_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap spacer_grey {
            get {
                object obj = ResourceManager.GetObject("spacer_grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap spacer_orange {
            get {
                object obj = ResourceManager.GetObject("spacer_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} or {1} to start recording..
        /// </summary>
        internal static string STATUS_STRIP_RECORD_MESSAGE {
            get {
                return ResourceManager.GetString("STATUS_STRIP_RECORD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} or {1} to stop recording..
        /// </summary>
        internal static string STATUS_STRIP_STOP_MESSAGE {
            get {
                return ResourceManager.GetString("STATUS_STRIP_STOP_MESSAGE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap stop_active_expertmode {
            get {
                object obj = ResourceManager.GetObject("stop_active_expertmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop_active_simplemode {
            get {
                object obj = ResourceManager.GetObject("stop_active_simplemode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop_inactive_expertmode {
            get {
                object obj = ResourceManager.GetObject("stop_inactive_expertmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .wav.
        /// </summary>
        internal static string WAV_EXTENSION {
            get {
                return ResourceManager.GetString("WAV_EXTENSION", resourceCulture);
            }
        }
    }
}
