//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLifter.DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLifter.DAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!-- LearnLift Dictionary File V2.0 --&gt;
        ///&lt;!--       (C) 2005 LearnLift       --&gt;
        ///&lt;dictionary id=&quot;&quot;&gt;
        ///  &lt;general&gt;
        ///    &lt;version&gt;267&lt;/version&gt;
        ///    &lt;author /&gt;
        ///    &lt;description /&gt;
        ///    &lt;category&gt;7&lt;/category&gt;
        ///    &lt;questioncaption /&gt;
        ///    &lt;answercaption /&gt;
        ///    &lt;sounddir&gt;Media&lt;/sounddir&gt;
        ///    &lt;commentsound id=&quot;0&quot; /&gt;
        ///    &lt;commentsound id=&quot;1&quot; /&gt;
        ///    &lt;commentsound id=&quot;2&quot; /&gt;
        ///    &lt;commentsound id=&quot;3&quot; /&gt;
        ///    &lt;commentsound id=&quot;4&quot; /&gt;
        ///    &lt;commentsound id=&quot;5&quot; /&gt;
        ///    &lt;comm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlankDictionaryV2_0 {
            get {
                return ResourceManager.GetString("BlankDictionaryV2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        internal static string BOX_NAME_POOL {
            get {
                return ResourceManager.GetString("BOX_NAME_POOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying card {0} of {1}....
        /// </summary>
        internal static string CARDS_COPYTO_STATUS {
            get {
                return ResourceManager.GetString("CARDS_COPYTO_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arts (old category).
        /// </summary>
        internal static string CATEGORYNAMES0 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth Sciences (old category).
        /// </summary>
        internal static string CATEGORYNAMES1 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Science (old category).
        /// </summary>
        internal static string CATEGORYNAMES10 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology (old category).
        /// </summary>
        internal static string CATEGORYNAMES11 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History (old category).
        /// </summary>
        internal static string CATEGORYNAMES2 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humanities (old category).
        /// </summary>
        internal static string CATEGORYNAMES3 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages (old category).
        /// </summary>
        internal static string CATEGORYNAMES4 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leisure (old category).
        /// </summary>
        internal static string CATEGORYNAMES5 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Sciences (old category).
        /// </summary>
        internal static string CATEGORYNAMES6 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous (old category).
        /// </summary>
        internal static string CATEGORYNAMES7 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politics (old category).
        /// </summary>
        internal static string CATEGORYNAMES8 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pure Sciences (old category).
        /// </summary>
        internal static string CATEGORYNAMES9 {
            get {
                return ResourceManager.GetString("CATEGORYNAMES9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter {0} - {1}.
        /// </summary>
        internal static string CHAPTER_FORMAT_STRING {
            get {
                return ResourceManager.GetString("CHAPTER_FORMAT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mlcfg.
        /// </summary>
        internal static string CONFIGURATION_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("CONFIGURATION_FILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new User....
        /// </summary>
        internal static string CREATE_NEW_USER {
            get {
                return ResourceManager.GetString("CREATE_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dzp.
        /// </summary>
        internal static string DICTIONARY_ARCHIVE_EXTENSION {
            get {
                return ResourceManager.GetString("DICTIONARY_ARCHIVE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pgsql://.
        /// </summary>
        internal static string DICTIONARY_DB_POSTGRES_CONNECTION_PREFIX {
            get {
                return ResourceManager.GetString("DICTIONARY_DB_POSTGRES_CONNECTION_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dip.
        /// </summary>
        internal static string DICTIONARY_DIP_EXTENSION {
            get {
                return ResourceManager.GetString("DICTIONARY_DIP_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mlm.
        /// </summary>
        internal static string DICTIONARY_EDB_EXTENSION {
            get {
                return ResourceManager.GetString("DICTIONARY_EDB_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .odf.
        /// </summary>
        internal static string DICTIONARY_ODF_EXTENSION {
            get {
                return ResourceManager.GetString("DICTIONARY_ODF_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml://.
        /// </summary>
        internal static string DICTIONARY_ODX_CONNECTION_PREFIX {
            get {
                return ResourceManager.GetString("DICTIONARY_ODX_CONNECTION_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .odx.
        /// </summary>
        internal static string DICTIONARY_ODX_EXTENSION {
            get {
                return ResourceManager.GetString("DICTIONARY_ODX_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .smlm.
        /// </summary>
        internal static string DICTIONARY_SYNCED_EDB_EXTENSION1 {
            get {
                return ResourceManager.GetString("DICTIONARY_SYNCED_EDB_EXTENSION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .zip.
        /// </summary>
        internal static string DICTIONARY_ZIP_EXTENSION {
            get {
                return ResourceManager.GetString("DICTIONARY_ZIP_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Learning Module format is not supported! ({0}).
        /// </summary>
        internal static string EXCEPTION_DICTIONARY_FORMAT_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("EXCEPTION_DICTIONARY_FORMAT_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Learning Module has been generated by an old version! ({0}).
        /// </summary>
        internal static string EXCEPTION_DICTIONARY_FORMAT_OLD_VERSION {
            get {
                return ResourceManager.GetString("EXCEPTION_DICTIONARY_FORMAT_OLD_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Learning Module path already exists! ({0}).
        /// </summary>
        internal static string EXCEPTION_DICTIONARY_PATH_EXISTS {
            get {
                return ResourceManager.GetString("EXCEPTION_DICTIONARY_PATH_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index access exception, cannot access card/chapter {0}..
        /// </summary>
        internal static string EXCEPTION_ID_ACCESS {
            get {
                return ResourceManager.GetString("EXCEPTION_ID_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID for this card is already used! ({0}).
        /// </summary>
        internal static string EXCEPTION_ID_EXISTS {
            get {
                return ResourceManager.GetString("EXCEPTION_ID_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index overflow, cannot add more than {0} cards/chapters..
        /// </summary>
        internal static string EXCEPTION_ID_OVERFLOW {
            get {
                return ResourceManager.GetString("EXCEPTION_ID_OVERFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This box does not exist! ({0}).
        /// </summary>
        internal static string EXCEPTION_INVALID_BOX {
            get {
                return ResourceManager.GetString("EXCEPTION_INVALID_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Learning Module!.
        /// </summary>
        internal static string EXCEPTION_INVALID_DICTIONARY {
            get {
                return ResourceManager.GetString("EXCEPTION_INVALID_DICTIONARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempt to import {0} failed!.
        /// </summary>
        internal static string EXCEPTION_INVALID_IMPORT_FORMAT {
            get {
                return ResourceManager.GetString("EXCEPTION_INVALID_IMPORT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid MemoryLifter Learning Module archive!.
        /// </summary>
        internal static string EXCEPTION_NO_VALID_ARCHIVE {
            get {
                return ResourceManager.GetString("EXCEPTION_NO_VALID_ARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MemoryLifter archive header is invalid!.
        /// </summary>
        internal static string EXCEPTION_NO_VALID_ARCHIVE_HEADER {
            get {
                return ResourceManager.GetString("EXCEPTION_NO_VALID_ARCHIVE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get a valid media filename! ({0}).
        /// </summary>
        internal static string EXCEPTION_NO_VALID_MEDIA_FILENAME {
            get {
                return ResourceManager.GetString("EXCEPTION_NO_VALID_MEDIA_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Learning Module could not be decrypted successfully..
        /// </summary>
        internal static string EXCEPTION_NOT_DECRYPTED {
            get {
                return ResourceManager.GetString("EXCEPTION_NOT_DECRYPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown connection prefix. ({0}).
        /// </summary>
        internal static string EXCEPTION_UNKNOWN_CONNECTIONPREFIX {
            get {
                return ResourceManager.GetString("EXCEPTION_UNKNOWN_CONNECTIONPREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown media file extension! ({0}).
        /// </summary>
        internal static string EXCEPTION_UNKNOWN_MEDIA {
            get {
                return ResourceManager.GetString("EXCEPTION_UNKNOWN_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported database type! ({0}).
        /// </summary>
        internal static string EXCEPTION_UNSUPPORTED_DATABASETYPE {
            get {
                return ResourceManager.GetString("EXCEPTION_UNSUPPORTED_DATABASETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add null value for a word..
        /// </summary>
        internal static string EXCEPTION_WORD_IS_NULL {
            get {
                return ResourceManager.GetString("EXCEPTION_WORD_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add null value to list of words..
        /// </summary>
        internal static string EXCEPTION_WORD_LIST_IS_NULL {
            get {
                return ResourceManager.GetString("EXCEPTION_WORD_LIST_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mlx.
        /// </summary>
        internal static string EXTENSION_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("EXTENSION_FILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        internal static string MergeDictionaryV2_0 {
            get {
                return ResourceManager.GetString("MergeDictionaryV2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP INDEX TextContent.idx_textcontent_cardsbyposition;
        ///CREATE NONCLUSTERED INDEX idx_textcontent_cardsbyposition ON TextContent 
        ///(
        ///	type ASC,
        ///	cards_id ASC,
        ///    [position] ASC
        ///);
        ///DROP INDEX Chapters.idx_chapters_lm_id;
        ///CREATE NONCLUSTERED INDEX idx_chapters_lm_id ON Chapters 
        ///(
        ///	lm_id ASC,
        ///    [position] ASC
        ///);
        ///DROP INDEX UserCardState.idx_textcontent_user_cards;
        ///CREATE NONCLUSTERED INDEX idx_textcontent_user_cards ON UserCardState 
        ///(
        ///	cards_id ASC,
        ///    [user_id] ASC
        ///);
        ///DROP INDEX Cards. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsSqlCeDbCreateIdxScript {
            get {
                return ResourceManager.GetString("MsSqlCeDbCreateIdxScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----(1) independed Tables
        ///--DROP TABLE Cards_MediaContent;
        ///--DROP TABLE MediaProperties;
        ///--DROP TABLE CommentarySounds;
        ///--DROP TABLE LearningModules_Cards;
        ///--DROP TABLE Chapters_Cards;
        ///--DROP TABLE SelectedLearnChapters;
        ///--DROP TABLE TextContent;
        ///--DROP TABLE LearnLog;
        ///--DROP TABLE UserCardState;
        ///--DROP TABLE UserProfilesLearningModulesSettings;
        ///--DROP TABLE LearningModules_Tags;
        ///--DROP TABLE MediaContent_Tags;
        ///--DROP TABLE MediaContent_CardStyles
        ///
        ///--DROP TABLE UserGroups_AccessControlList;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsSqlCeDbCreateScript {
            get {
                return ResourceManager.GetString("MsSqlCeDbCreateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Sciences.
        /// </summary>
        internal static string NEWCATEGORYNAMES0 {
            get {
                return ResourceManager.GetString("NEWCATEGORYNAMES0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arts.
        /// </summary>
        internal static string NEWCATEGORYNAMES1 {
            get {
                return ResourceManager.GetString("NEWCATEGORYNAMES1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string NEWCATEGORYNAMES2 {
            get {
                return ResourceManager.GetString("NEWCATEGORYNAMES2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string NEWCATEGORYNAMES3 {
            get {
                return ResourceManager.GetString("NEWCATEGORYNAMES3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Sciences.
        /// </summary>
        internal static string NEWCATEGORYNAMES4 {
            get {
                return ResourceManager.GetString("NEWCATEGORYNAMES4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Sciences.
        /// </summary>
        internal static string NEWCATEGORYNAMES5 {
            get {
                return ResourceManager.GetString("NEWCATEGORYNAMES5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryLifter Packed Dictionary, Category {0}.
        /// </summary>
        internal static string PACKER_ARCHIVE_HEADER_COMMENT_PACK {
            get {
                return ResourceManager.GetString("PACKER_ARCHIVE_HEADER_COMMENT_PACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryLifter Packed Dictionary.
        /// </summary>
        internal static string PACKER_ARCHIVE_HEADER_COMMENT_UNPACK {
            get {
                return ResourceManager.GetString("PACKER_ARCHIVE_HEADER_COMMENT_UNPACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryLifter Stick.
        /// </summary>
        internal static string StickUserName {
            get {
                return ResourceManager.GetString("StickUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup ({0}) of {1}.
        /// </summary>
        internal static string XML_BACKUP_FILENAME {
            get {
                return ResourceManager.GetString("XML_BACKUP_FILENAME", resourceCulture);
            }
        }
    }
}
